# Generated by Django 5.0.3 on 2024-04-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(choices=[('completed', 'completed'), ('pending', 'pending')], default=False, max_length=200)),
            ],
        ),
    ]
